### ISSUE TITLE
Error: Could not find or load main class abapspace.ABAPSpace

### ISSUE THREAD

**Issue by nathanss** [SAPAssets/ABAPSpace#1]
Hello,

Very interested in the tool.

I am running RHEL 7 and built the abapspace.gui and abapspace.core with gradle just as described and the build appears to be OK.

When I try to run the script "abapspace.gui/build/scripts/abapspace I get the following error:
Error: Could not find or load main class abapspace.ABAPSpace

Do you know what could it be? Feel free to ask me for additional info.

**Comment by nathanss** [comment]
Hey, sorry about that. Didn't figured that I could download the release
binaries.

Will do that and test the tool!

Thanks!

2018-05-04 16:20 GMT-03:00 mnemotron <notifications@github.com>:

**Comment by nathanss** [comment]
I'll be closing the issue.

**Comment by mnemotron** [comment]
Thanx.
