### ISSUE TITLE
Case sensitivity is not respected

### ISSUE THREAD

**Issue by nathanss** [SAPAssets/ABAPSpace#4]
Hello,

Although in ABAP many parts are case insensitive, I've discovered through the hard way, while facing bugs while trying to use abapGit to convert namespaces, that you need to respect case sensitivity in abapGit.

For example, when applying the conversion, I've seen that in some places the tool changed from "/NNNN/ESP_ACTIVITY_WRAPPER" to "zesp_activity_wrapper". 

Perhaps on this example nothing would happen, but in some cases it can crash abapGit, specially in data elements and tables, I think.

It would be best to perform two searches, one for the lower case version (from /nnnn/ to z) and one for the upper case version (from /NNNN/ to Z).

**Comment by mnemotron** [comment]
Good point. I'll take it into account. Thanx.

**Comment by nathanss** [comment]
Hello,

Now it works!
